### DISCUSSION TITLE
How to set uid/gid in docker compose file with rootless?

### DISCUSSION THREAD

**Discussion by adoyle-h** [CorentinTh/enclosed#305] [Q&A] [answered]
I'm using rootless image. How to set uid/gid in docker compose file?

I tried below config, but it prints logs `EACCES: permission denied, open '/app/.data/...'`.

```yaml
services:
  enclosed:
    image: corentinth/enclosed:latest-rootless
    ports:
      - 8787:8787
    volumes:
      - ./enclosed-data:/app/.data
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
```

**Comment by CorentinTh** [comment, marked as answer]
Hi @adoyle-h 

To set the UID and GID correctly in a rootless Docker container, you can specify them directly in your `docker-compose.yml` file by using the `user` property. Update your `docker-compose.yml` like this:

```yaml
services:
  enclosed:
    image: corentinth/enclosed:latest-rootless
    ports:
      - 8787:8787
    volumes:
      - ./enclosed-data:/app/.data
    restart: unless-stopped
    user: "1000:1000"  # Set UID and GID here
```

Also make sure the enclosed-data directory on your host has permissions that match UID 1000 and GID 1000. You can update the permissions with:

```bash
sudo chown -R 1000:1000 ./enclosed-data
```

Let me know if this resolves the issue or if you encounter any other problems
