### ISSUE TITLE
Add `AUTHENTICATION_USERS_FILE` support

### ISSUE THREAD

**Issue by NuroDev** [CorentinTh/enclosed#426]
### What type of request is this?

Enhancement of an existing feature

### Clear and concise description of the feature you are proposing

Many self-hosted projects offer support for a `_FILE` suffix for certain environment variables in order to read from a file instead of relying on environment variables directly passing in a value.

It would be good if `AUTHENTICATION_USERS_FILE` support could be added in order to store user credentials with Docker Secrets instead of keeping them in a `.env` file or something similar.

### Example
```yaml
# docker-compose.yml
secrets:
  enclosed_users:
    external: true

volumes:
  enclosed_data:

services:
  enclosed:
    image: ghcr.io/corentinth/enclosed:latest
    secrets:
      - enclosed_users
    environment:
      AUTHENTICATION_USERS_FILE: /run/secrets/enclosed_users
    volumes:
      - enclosed_data:/app/.data
```

If I get some time free soon I am happy to take a look into implementing this feature / change myself & putting up a PR for it if need be.

### Validations

- [x] Check the feature is not already implemented in the project.
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] Check that the feature is technically feasible and aligns with the project's goals.
